
name: Frontend IPFS deployment

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install Dependencies
        run: npm install --prefix ./frontend && npm install -g ipfs-http-client

      - name: Build frontend
        run: npm run build --prefix ./frontend

#      - name: Rename build folder
#        run: mkdir ./frontend/SENTINEL && mv ./frontend/build ./frontend/SENTINEL

      - name: Publish to IPFS
        run: node ./frontend/scripts/publish.js ${{ secrets.IPFS_HOST }} ../build
      
# https://ipfs.io/ipns/k51qzi5uqu5dmjabueumy621fbdczkie0z0sa1vq57kjet242lcum9opm1qvbl