
name: Frontend IPFS deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install Dependencies
        run: npm install --prefix ./frontend && npm install -g ipfs-http-client

      - name: Build frontend
        run: npm run build --prefix ./frontend

      - name: Print dirs
        run: ls -la ./frontend
        
      - name: Publish to IPFS
        run: node ./frontend/scripts/publish.js ${{ secrets.IPFS_HOST }} ./frontend/build
