# Reference: https://github.com/marketplace/actions/setup-node-js-environment 
# workflow from: https://github.com/limcheekin/eth-dapps-nextjs-boiletplate/blob/master/.github/workflows/truffle.yml

name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Show NodeJS version    
      run: npm --version

    - name: Install Dependencies
      run: npm install --prefix ./frontend 
    
    - name: Install Ganache CLI 
      run: npm install -g ganache

    - name: Start Ganache
      run: ganache --detach --server.port=7545 --wallet.accounts="0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63","0X56BC75E2D63100000"

    - name: Run Tests
      run: npm test --prefix ./frontend 
