# Reference: https://github.com/marketplace/actions/setup-node-js-environment 
# workflow from: https://github.com/limcheekin/eth-dapps-nextjs-boiletplate/blob/master/.github/workflows/truffle.yml

name: Truffle Build

on:
  pull_request: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Show NodeJS version    
      run: npm --version
    
    - name: Install Truffle
      run: npm install truffle@5.7.6 -g # cannot use truffle@latest due to https://github.com/sc-forks/solidity-coverage/issues/696
    
    - name: Install Truffle Dependencies
      run: npm install      
    
    - name: Run Truffle Test
      run: truffle test 
